
const library = {
    'Teach Yourself Computer Science' : 'https://teachyourselfcs.com/',
    'CS3 Data Structures and Algorithms': 'https://opendsa-server.cs.vt.edu/OpenDSA/Books/CS3/html/IntroDSA.html',
    'The Architecture of Open Source Applications' : 'https://aosabook.org/en/index.html#fh-cover',
    'Software Design by Example in Python' : 'https://third-bit.com/sdxpy/',
    'Software Design by Example in JavaScript' : 'https://third-bit.com/sdxjs/',
    'Learn to Program: by example' : 'https://leanpub.com/learning-to-program-by-example',
    'What to Look for in a Code Review' : 'https://leanpub.com/whattolookforinacodereview',
    'Learn Programming - Your Guided Tour Through the Programming Jungle' : 'https://progbook.org/',
    'Patterns for Beginning Programmers: With Examples in Java' : 'https://pressbooks.lib.jmu.edu/programmingpatterns/',
    'Your First Year in Code' : 'https://leanpub.com/firstyearincode',
    'The Recursive Book of Recursion' : 'https://nostarch.com/recursive-book-recursion',
    'The Recursive Book of Recursion' : 'https://inventwithpython.com/recursion/',
    'How to Design Programs: An Introduction to Programming and Computing' : 'https://htdp.org/',
    'Programming Fundamentals' : 'https://press.rebus.community/programmingfundamentals/',
    'The Practical Theory of Programming' : 'https://www.cs.toronto.edu/~hehner/aPToP/',
    'Formal Methods of Software Design' : 'http://www.cs.utoronto.ca/~hehner/FMSD/',
    'Data Structures and Algorithms in Python' : 'https://web.archive.org/web/20160620193501/http://www.brpreiss.com:80/books/opus7/',
    'Google Style Guide' : 'https://google.github.io/styleguide/',
    'Data Structures and Algorithms Using C' : 'https://csit.ust.edu.sd/files/2019/10/Data-structure-using-C-1.pdf',
    'The Art and Craft of Programming' : 'https://www.cs.cmu.edu/afs/cs/user/jcr/ftp/craftprog.pdf',
    'Notes on Data Structures and Programming Techniques in C' : 'https://www.iare.ac.in/sites/default/files/DS_NOTES_BY_Dr_L_V_NARASIMHA_PRASAD.pdf',
    'Notes on Data Structures and Programming Techniques (CPSC 223, Spring 2022)' : 'https://www.cs.yale.edu/homes/aspnes/classes/223/notes.html',
    'Static Site Generators' : 'https://www.oreilly.com/content/static-site-generators/',
    'Static Site Generators' : 'https://chrisdaaz.github.io/static-web-scholcomm/tutorials/static-site-generators/',
    'Static Site Generators' : 'https://github.com/ffisk/books/blob/master/static-site-generators.pdf',
    'Static Site Generators: Powerful Publishing with Less Infrastructure' : 'https://librarypublishing.org/wp-content/uploads/2019/06/LPF19-Static-Site-Generators.pdf',
    'Research Based Web Design and Usability Guidelines' : 'https://digital.gov/topics/usability/',
    'Research Based Web Design and Usability Guidelines' : 'https://commons.erau.edu/publication/1028/',
    'The Web Project Guide' : 'https://webproject.guide/',
    'The Missing Link: An Introduction to Web Development and Programming' : 'https://milnepublishing.geneseo.edu/themissinglink/',
    'Building Front-End Web Apps with Plain JavaScript' : 'https://web-engineering.info/JsFrontendApp-Book/',
    'Building Back-End Web Apps with Java, JPA and JSF' : 'https://web-engineering.info/JavaJpaJsfApp-Book/',
    'Web Applications with JavaScript or Java' : 'https://web-engineering.info/_includes/book/WebApp1/',
    'How to Build a Website with CSS and HTML' : 'https://www.digitalocean.com/community/books/how-to-build-a-website-with-css-and-html-ebook',
    'Scalable and Modular Architecture for CSS' : 'http://smacss.com/book/',
    'Adaptive Web Design: Crafting Rich Experiences with Progressive Enhancement' : 'https://adaptivewebdesign.info/1st-edition/read/',
    'Algorithms Lecture Notes' : 'https://jeffe.cs.illinois.edu/teaching/algorithms/',
    'The Little Book of Algorithms' : 'https://www.mrlaulearning.com/2020/06/LBOA2.html',
    'Think Data Structures' : 'https://greenteapress.com/wp/think-data-structures/',
    'Data Structures and Information Retrieval in Python' : 'https://allendowney.github.io/DSIRP/',
    'Algorithms for Sparse Linear Systems' : 'https://link.springer.com/book/10.1007/978-3-031-25820-6',
    'The Everyday Life of an Algorithm' : 'https://link.springer.com/book/10.1007/978-3-030-00578-8',
    'Algorithms for Optimization | Decision Making | Validation' : 'https://algorithmsbook.com/',
    'The Design of Approximation Algorithms' : 'https://www.designofapproxalgs.com/download.php',
    'Planning Algorithms' : 'https://lavalle.pl/planning/',
    'Essential Coding Theory' : 'https://cse.buffalo.edu/faculty/atri/courses/coding-theory/book/',
    'Python and Coding Theory' : 'https://freecomputerbooks.com/books/joyner_python-notes.pdf',
    'The Super Programmer: A COlorful Introduction to Engineering' : 'https://keyvan.me/tsp/',
    'CoderSpeak: The Language of Computer Programmers' : 'https://uclpress.co.uk/book/coderspeak/',
    'Programming Problems: Advanced Algorithms' : 'https://www.smashwords.com/books/view/318007',
    'Programming Problems: A Primer for The Technical Interview' : 'https://www.smashwords.com/books/154895',
    'Programming Problems in Java: A Primer for the Technical Interview' : 'https://www.smashwords.com/books/view/544180',
    'The Code Challenge Book: How to Ace the Coding Bootcamp Technical Interview' : 'https://s3.amazonaws.com/coderbytestaticimages/CoderbyteEbook.pdf',
    'Live Coding: A User&apos;s Manual' : 'https://direct.mit.edu/books/oa-monograph/5495/Live-CodingA-User-s-Manual',
    'Structure and Interpretation of Computer Programs - JavaScript Edition' : 'https://sourceacademy.org/sicpjs/index',
    'Structure and Interpretation of Computer Programs - Lisp Schema' : 'https://sarabander.github.io/sicp/html/index.xhtml',
    'Software Design for Flexibility: How to Avoid Programming Yourself into a Corner' : 'https://mitpress.ublish.com/ebook/software-design-for-flexibility-preview/12618/iii',
    'Isomorphism - Mathematics of Programming' : 'https://www.oldergeeks.com/downloads/files/Isomorphism%20English.pdf',
    'Answer Set Programming (ASP)' : 'https://www.cs.utexas.edu/~vl/teaching/378/ASP.pdf',
    'Aesthetic Programming' : 'https://openhumanitiespress.org/books/titles/aesthetic-programming/',
    'Competitive Programmer&apos;s Handbook' : 'https://usaco.guide/CPH.pdf',
    'Principles of Algorithmic Problem Solving' : 'https://www.csc.kth.se/~jsannemo/slask/main.pdf',
    'The Black Art of Programming' : 'http://uploads.worldlibrary.net/uploads/pdf/20130921093033the_black_art_of_programming.pdf',
    'Concepts, Techniques and Models of Computer Programming' : 'https://github.com/avikalpg/POPL/blob/master/Peter%20Van%20Roy%2C%20Seif%20Haridi-Concepts%2C%20techniques%2C%20and%20models%20of%20computer%20programming-MIT%20Press%20(2004).pdf',
    'OOP: Learn Object Oriented Thinking and Programming' : 'https://pub.bruckner.cz/titles/oop',
    'Programming Persistent Memory' : 'https://link.springer.com/book/10.1007/978-1-4842-4932-1',
    'What Every Programmer Should Know About Memory' : 'https://akkadia.org/drepper/cpumemory.pdf',
    'Software Foundations' : 'https://softwarefoundations.cis.upenn.edu/',
    'Computing FUndamentals: The theory and Practice of Software Design' : 'https://cslab.pepperdine.edu/warford/ComputingFundamentals/',
    'Programming and Mathematical Thinking: A Gentle Introduction to Discrete Math Featuring Python' : 'https://webpages.math.luc.edu/~lauve/courses/215-fa2016/Stavely_python_ebook.pdf',
    'The Art of Readable Code' : 'https://mcusoft.wordpress.com/wp-content/uploads/2015/04/the-art-of-readable-code.pdf',
    'Computer Science Logo Style Volume 1: Symbolic Computing' : 'https://people.eecs.berkeley.edu/~bh/v1-toc2.html',
    'Computer Science Logo Style Volume 2: Advanced Techniques' : 'https://people.eecs.berkeley.edu/~bh/v2-toc2.html',
    'Computer Science Logo Style Volume 3: Beyond Programming' : 'https://people.eecs.berkeley.edu/~bh/v3-toc2.html',
    '500 Lines or Less: Experienced Programmers Solve Interesting Problems' : 'https://aosabook.org/en/index.html#500lines',
    'A Problem Course in Mathematical Logic' : 'http://euclid.trentu.ca/math/sb/pcml/',
    'Algorithms and Programming: Problems and Solutions' : 'https://doc.lagout.org/science/0_Computer%20Science/2_Algorithms/Algorithms%20and%20Programming_%20Problems%20and%20Solutions%20%282nd%20ed.%29%20%5BShen%202009-12-17%5D.pdf',
    'How to Solve It: A New Aspect of Mathematical Method' : 'https://press.princeton.edu/books/paperback/9780691164076/how-to-solve-it?srsltid=AfmBOooLDf_ONP7pFCRBITpTV59IRbjOZwf8OX5dRKlQaX1dGDeDmxGN',
    'Programming Paradigms for Dummies: What Every Programmer Should Know' : 'https://webperso.info.ucl.ac.be/%7Epvr/VanRoyChapter.pdf',
    'Crafting Interpreters' : 'https://craftinginterpreters.com/contents.html',
    'Composing Programs' : 'https://www.composingprograms.com/',
    'Computational and Inferential Thinking: The Foundations of Data Science (Data 8)' : 'https://inferentialthinking.com/chapters/intro.html',
    'UC Berkeley Data 8' : 'http://www.data8.org/',
    'Building a Modern Computer From First Principle' : 'https://www.nand2tetris.org/',
    '[Course] Deep Dive Into Modern Web Development' : 'https://fullstackopen.com/en/',
    'Let&apos;s Build a Compiler' : 'https://compilers.iecc.com/crenshaw/',
    'ELoquent JavaScript' : 'https://eloquentjavascript.net/',
    'Learn Rest API Design' : 'https://restapitutorial.com/',
    '[Course] The Missing Semester of your CS Education' : 'https://missing.csail.mit.edu/about/',
    '[Course] Great Practical Ideas in CS' : 'https://www.cs.cmu.edu/~15131/f17/',
    'The Coding Career Handbook' : 'https://learninpublic.org/?from=swyxdotio-LIP',
}